### ISSUE TITLE
Change environment drop down, workers don’t update

### ISSUE THREAD

**Issue by saul-data** [dataplane-app/dataplane#331]
To reproduce:
1. Go to workers under development environment 
2. Click to expand the worker group
3. Change the environment to production

The same workers remain.

**Comment by onattech** [comment]
Submitted a pr for this issue. https://github.com/dataplane-app/dataplane/pull/332

**Comment by saul-data** [comment]
Fixed per pull request https://github.com/dataplane-app/dataplane/pull/332
