### ISSUE TITLE
User experience - dont show datetime in logs in code editor

### ISSUE THREAD

**Issue by saul-data** [dataplane-app/dataplane#359]
The date and time in the log doesn't add value and confuses reading the output when developing. Maybe put a datetime at begin and end with timing. 

<img width="1678" alt="image" src="https://user-images.githubusercontent.com/63714857/187677531-50cd581d-fb2b-4813-a27e-bae5de5b6dfb.png">

**Comment by onattech** [comment]
Here's the pr for this issue. https://github.com/dataplane-app/dataplane/pull/376

**Comment by saul-data** [comment]
Fixed in release https://github.com/dataplane-app/dataplane/releases/tag/v0.1.2
