### ISSUE TITLE
[Bug][Install]docker-compose deployment failed

### ISSUE THREAD

**Issue by ChenpiDog** [dataplane-app/dataplane#443]
![image](https://user-images.githubusercontent.com/55483982/195963203-d8e77473-e2dd-4bd3-a1cf-c7859c38668e.png)
failed to connect to `host=postgres user=postgres database=dataplane`

**Comment by ChenpiDog** [comment]
When I deployed the second time, it was successful!
![image](https://user-images.githubusercontent.com/55483982/195963440-003564d0-cf11-44a3-a202-194bf4995644.png)

**Comment by saul-data** [comment]
I think this might be normal behaviour. The main application and workers are written in Golang and compiled to machine code, they tend to spin up much faster than first initialisation of Postgresql / Timescaledb - which does take time on Postgresql's first run and only starts accepting connections once ready. That is why Dataplane has been designed to be resilient to database connections by retrying the database connection until the database is ready. I couldn't replicate the issue on my side. I am going to close the ticket but I will keep an eye out for anyone else who may have a similar experience as you.
