### ISSUE TITLE
Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by zhangjinrui2718** [dataplane-app/dataplane#513]
when i drag the second python component into the canvas , it shows this error

![image](https://user-images.githubusercontent.com/20435889/209305229-22f90aa5-98b1-4c3f-8687-c74299a4b38f.png)

the version i used:

CONTAINER ID   IMAGE                                      COMMAND                  CREATED              STATUS                            PORTS                          NAMES
751bc4d586d4   nats:2.7.4-scratch                         "/nats-server --clus…"   About a minute ago   Up 5 seconds                      4222/tcp, 6222/tcp, 8222/tcp   download_nats_1
37a63c61b9d0   dataplane/dataplane-worker-python:latest   "./dataplane-worker"     About a minute ago   Up 5 seconds                                                     download_dataplane-worker_1
01534d135d9d   timescale/timescaledb:2.5.1-pg14           "docker-entrypoint.s…"   About a minute ago   Up 5 seconds (health: starting)   5432/tcp                       download_postgres_1
0bbf5100410b   redis:7.0.5-bullseye                       "docker-entrypoint.s…"   About a minute ago   Up 5 seconds (healthy)            0.0.0.0:49158->6379/tcp        download_redis-service_1
1cd2594ff42e   dataplane/dataplane-worker-python:latest   "./dataplane-worker"     About a minute ago   Up 5 seconds                                                     download_dataplane-worker-prod_1
1167e5feba56   dataplane/dataplane:latest                 "./dataplane"            About a minute ago   Up 5 seconds                      0.0.0.0:9001->9001/tcp         download_mainapp_1

**Comment by zhangjinrui2718** [comment]
![image](https://user-images.githubusercontent.com/20435889/209307085-03d9f264-fbed-49ad-847c-d64baffbecb8.png)


i found a secret
maybe the error is associated with this line.  haha

**Comment by saul-data** [comment]
@zhangjinrui2718 thanks for reporting, we are looking into it and will write automated tests to find this error for the future :)

**Comment by saul-data** [comment]
@zhangjinrui2718  - I just released a fix, can you please test by pulling the latest docker image dataplane/dataplane:V0.3.2?

<img width="1679" alt="image" src="https://user-images.githubusercontent.com/63714857/209338152-b9137c77-f66d-473f-bd1a-ea00ed6045a8.png">

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/63714857/209338404-d1f9141b-4cfa-493f-9315-270e058b860c.png">

**Comment by zhangjinrui2718** [comment]
ok i will try it thank u

**Comment by zhangjinrui2718** [comment]
it fixed

**Comment by saul-data** [comment]
🎉🎉🎉
