### ISSUE TITLE
python packages not found

### ISSUE THREAD

**Issue by zhangjinrui2718** [dataplane-app/dataplane#525]
after create a pipeline in dev-env with some python packages  , i deply it into the prod-env's worker
when i click the run button , it shows me the error " import xxx module not found"

where can i install the python package in the prod-env

**Comment by saul-data** [comment]
@zhangjinrui2718  - please follow these steps:

1. Create a dummy pipeline in Production environment
2. Open code editor for one of the nodes
3. Update requirements.txt file and click Install

Your deployments in production will then have the correct Python packages. Let me know if that works. 

I have written that a note that this isn't intuitive and needs better product design from our side.

**Comment by zhangjinrui2718** [comment]
ok,3q
i entered the container and use 'pip' to install the dependency

maybe the requirements file should be packaged in to the task-code , it could be installed automatically when deploying a pipeline

**Comment by saul-data** [comment]
Yes I agree with this, we need to prompt the user to confirm packages to be installed on production when deploying.
