### ISSUE TITLE
API trigger on deployment to another environment

### ISSUE THREAD

**Issue by saul-data** [dataplane-app/dataplane#592]
1. The API trigger url doesn't have the ID in url - it would not know where to route the trigger to
2. To configure API triggers, user needs to click edit pipeline then configure API, similar to time schedule this should be direct
3. Version conflicts between environments so if the same version of the trigger API pipeline is on one environment, it will conflict with another environment.

**Comment by onattech** [comment]
Number 2 is fixed and pushed.
