### ISSUE TITLE
API trigger returning nothing

### ISSUE THREAD

**Issue by marconimedeiros2** [dataplane-app/dataplane#669]
I'm trying to use the trigger features via API but no information is returned.

1) I checked the Redis database (where API data is recorded for up to 24 hours) and there is never anything either
2) The output is always empty and len = 0 (zero)

I need help with:
1) How do I identify where the problem is?
2) How do I view the Redis database without using external tools, just docker?

**Comment by saul-data** [comment]
Hi there, I need a bit more information to try assist here. Are you using the standard docker compose setup?  Does the pipeline get triggered? Are you calling the api within docker network or from outside docker? What is the response from the api call?

**Comment by marconimedeiros2** [comment]
Great questions! 

1) I'm using the original docker-compose file, anyone modification
2) My server only runs this application, without OS changes (Ubuntu)
3) I'm calling the API from out of the network and docker, from Google Colab script.
4) It returns status code 200 in message with the unique id. When I run the script at Dataplane (the original, getting the data from env) nothing returns beyonds the print strings.
5)  When I check the Redis server INSIDE the Docker I can found only one key called "ping" and sometimes this is not there.

What more can I offer to you about informations?

**Comment by saul-data** [comment]
That is helpful thanks. 

So you are having an issue with this part:
https://dataplane.app/docs/api-trigger#using-data-from-the-body-of-an-api-call

What happens if you add something like this in your first node. What is the output?

```python
import os, json

if __name__ == "__main__":

    print("My data: "+os.environ["DP_API_DATA"])

    x = json.loads(os.environ["DP_API_DATA"])

    print("Output:")
    print(x)

```

**Comment by marconimedeiros2** [comment]
> ```python
> import os, json
> 
> if __name__ == "__main__":
> 
>     print("My data: "+os.environ["DP_API_DATA"])
> 
>     x = json.loads(os.environ["DP_API_DATA"])
> 
>     print("Output:")
>     print(x)
> ```

After run a CURL to the URL and run the script above:

```
2024/04/27 15:56:57 Run
My data: 
Output:
Run time: 684.938613ms
2024/04/27 15:56:57 Success
```

Anything is returned.

**Comment by marconimedeiros2** [comment]
See the video with original method:

https://youtu.be/nC4z9E2vwb8

**Comment by marconimedeiros2** [comment]
It's working! I think was the new code you in doc. Maybe is interesting change it to the Dataplane examples code.

**Comment by saul-data** [comment]
Glad it is working! 🎉🎉
