### ISSUE TITLE
Lost access to scripts

### ISSUE THREAD

**Issue by marconimedeiros2** [dataplane-app/dataplane#670]
I lost access to the virtual machine that was running Dataplane, however, I managed to rescue the virtual storage disk.

I would like to know how I can manually restore the script files, please!

If anyone knows how to restore Docker containers as well, that would be a great help!

**_I have a docker folder avaliable to share in private._**

**Comment by saul-data** [comment]
The scripts are stored on the database. It is recommended to keep the database backed up.
